version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      all:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    commit-message:
      # since a deps update is significant for this package,
      # don't use chore for non-dev updates
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
