name: publish
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc'
      - '.eslintrc.js'
      - '.eslintrc.react.js'
      - '.prettierrc.js'
      - 'tsconfig.json'
      - '.github/workflows/publish.yml'
jobs:
  preview:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - name: git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      # not dry-run, but this job doesn't commit or push anything anyway
      # required to get the actual bumped version
      - run: yarn standard-version
      # yarn doesn't have an equivalent preview
      - run: npm publish --dry-run
      - id: version
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const version = require('./package.json').version
            core.warning(`Approving this deployment will publish version ${version}`)
            return version
  publish:
    needs: [preview]
    runs-on: ubuntu-latest
    environment:
      name: NPM
      url: https://www.npmjs.com/package/@nihalgonsalves/esconfig/v/${{ needs.preview.outputs.version }}
    steps:
      - name: git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn standard-version
      - name: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --non-interactive --access public
      - run: git push --follow-tags origin main
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          tag_name: v${{ needs.preview.outputs.version }}
