name: publish
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'eslint-rules-base.js'
      - '.eslintrc'
      - '.eslintrc.js'
      - '.eslintrc.react.js'
      - '.prettierrc.js'
      - 'tsconfig.json'
      - '.github/workflows/publish.yml'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  preview:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - name: git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      # not dry-run, but this job doesn't commit or push anything anyway
      # required to get the actual bumped version
      - run: yarn standard-version
      # yarn doesn't have an equivalent preview
      - run: npm publish --dry-run
      - id: version
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const version = require('./package.json').version
            core.warning(`Approving this deployment will publish version ${version}`)
            return version

  release:
    needs: [preview]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@nihalgonsalves/esconfig'
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

  publish:
    if: ${{ needs.release.outputs.release_created }}
    needs: [preview, release]
    runs-on: ubuntu-latest
    environment:
      name: NPM
      url: https://www.npmjs.com/package/@nihalgonsalves/esconfig/v/${{ needs.preview.outputs.version }}
    steps:
      - name: git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn standard-version
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # yarn doesn't have an equivalent --provenance
        run: npm publish --provenance --access public
      - run: git push --follow-tags origin main
